/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Systems
         * @description Registered systems, the default (used when a request names none) first. Empty when no
         *     model is configured; ``/check`` and ``/scan`` then return 503.
         */
        get: operations["list_systems_systems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Jobs since the server started, newest first.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/jira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Jira Sync
         * @description Sync issues updated since the last run (or all, with ``full``). Poll ``/jobs/{id}``;
         *     ``progress`` counts issues synced so far.
         */
        post: operations["start_jira_sync_sync_jira_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync State
         * @description Watermark per source: everything updated before it has been synced.
         */
        get: operations["sync_state_sync_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Issues
         * @description Newest first. Version filters match a version name exactly; they don't compare versions.
         */
        get: operations["list_issues_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Issue */
        get: operations["get_issue_issues__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description Oldest first, ordered by the version module (3.9.0 before 3.10.0). Names that don't
         *     parse as versions come last.
         */
        get: operations["list_versions_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check
         * @description Is ``kafka_version`` affected by the issue? Decided by code from cited facts; the answer
         *     may be ``insufficient_information``. 503 until a system is registered.
         */
        post: operations["check_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Scan
         * @description Answer each candidate issue for ``kafka_version``: affected, not_affected or
         *     insufficient_information, with cited facts and a link. Poll ``/jobs/{id}``; ``progress``
         *     counts issues answered, and ``result`` is a ``ScanResponse``. One scan per system at a
         *     time, since they share the model server.
         */
        post: operations["start_scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_eval_datasets_get"];
        put?: never;
        /**
         * Sample Dataset
         * @description Sample issues and write a new dataset with an empty ``labels.csv``.
         */
        post: operations["sample_dataset_eval_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/datasets/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset Status
         * @description Labeling progress and problems.
         */
        get: operations["dataset_status_eval_datasets__name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/datasets/{name}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Dataset
         * @description Upload a fully labeled dataset to Langfuse.
         */
        post: operations["upload_dataset_eval_datasets__name__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Saved local runs, newest first.
         */
        get: operations["list_runs_eval_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Score a system on the dataset. Poll ``/jobs/{id}``; the result has the metrics, and local
         *     runs are saved under ``/eval/runs``.
         */
        post: operations["start_run_eval_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/runs/{dataset}/{run_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_eval_runs__dataset___run_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckRequest */
        CheckRequest: {
            /** Issue Key */
            issue_key: string;
            /**
             * Kafka Version
             * @example 3.6.1
             */
            kafka_version: string;
            /**
             * System
             * @description Default: the first registered system
             */
            system?: string | null;
        };
        /** CheckResponse */
        CheckResponse: {
            /** Issue Key */
            issue_key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Kafka Version */
            kafka_version: string;
            /**
             * Answer
             * @enum {string}
             */
            answer: "affected" | "not_affected" | "insufficient_information";
            /** System */
            system: string;
            /**
             * Decided By
             * @description fix_versions when JIRA's fix versions settle it (the system isn't called); otherwise the system
             */
            decided_by: string;
            /**
             * Cached
             * @description The system's facts were stored from an earlier run
             */
            cached: boolean;
            /**
             * Fix Versions
             * @description Given as structured input, from JIRA
             */
            fix_versions: string[];
            /**
             * Evidence
             * @description Cited facts the decision used
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Dropped
             * @description Facts rejected, with the reason
             */
            dropped: components["schemas"]["DroppedEvidenceOut"][];
        };
        /** Comment */
        Comment: {
            /** Author */
            author: string | null;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DatasetStatus */
        DatasetStatus: {
            /** Name */
            name: string;
            /** Labeled */
            labeled: number;
            /** Total */
            total: number;
            /**
             * Problems
             * @description Problems other than unlabeled cases
             */
            problems: string[];
            /**
             * Ready
             * @description Fully labeled with no problems; can be uploaded
             */
            ready: boolean;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Name */
            name: string;
            /** Design */
            design: string;
            /** Labeled */
            labeled: number;
            /** Total */
            total: number;
        };
        /** DroppedEvidenceOut */
        DroppedEvidenceOut: {
            /** Version */
            version: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "introduced" | "affects" | "unaffected" | "fix";
            /** Quote */
            quote: string;
            /** Reason */
            reason: string;
        };
        /** EvalRun */
        EvalRun: {
            /** Run Name */
            run_name: string;
            /** System */
            system: string;
            /** Dataset */
            dataset: string;
            /** Provisional */
            provisional: boolean;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** EvalRunRequest */
        EvalRunRequest: {
            /**
             * Dataset
             * @default kafka-ground-truth-v2
             */
            dataset?: string;
            /**
             * System
             * @description A registered system; runs are compared with each other
             */
            system: string;
            /**
             * Run Name
             * @description Default: <system>-<UTC timestamp>
             */
            run_name?: string | null;
            /**
             * Provisional
             * @description Score against JIRA metadata answers; allowed before labeling is done
             * @default false
             */
            provisional?: boolean;
            /**
             * Langfuse
             * @description Run as a Langfuse experiment on the dataset
             * @default false
             */
            langfuse?: boolean;
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Run Name */
            run_name: string;
            /** System */
            system: string;
            /** Dataset */
            dataset: string;
            /** Provisional */
            provisional: boolean;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Version */
            version: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "introduced" | "affects" | "unaffected" | "fix";
            /** Quote */
            quote: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Db Revision */
            db_revision: string | null;
        };
        /** IssueDetail */
        IssueDetail: {
            /** Key */
            key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Issue Type */
            issue_type: string | null;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /** Priority */
            priority: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Project */
            project: string;
            /** Description */
            description: string | null;
            /** Labels */
            labels: string[];
            /** Components */
            components: string[];
            /** Affects Versions */
            affects_versions: string[];
            /** Fix Versions */
            fix_versions: string[];
            /** Comments */
            comments: components["schemas"]["Comment"][];
        };
        /** IssuePage */
        IssuePage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["IssueSummary"][];
        };
        /** IssueSummary */
        IssueSummary: {
            /** Key */
            key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Issue Type */
            issue_type: string | null;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /** Priority */
            priority: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Key */
            key: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Progress */
            progress: number;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** KafkaVersion */
        KafkaVersion: {
            /** Name */
            name: string;
            /** Released */
            released: boolean;
            /** Archived */
            archived: boolean;
            /** Release Date */
            release_date: string | null;
        };
        /** SampleRequest */
        SampleRequest: {
            /** Name */
            name: string;
            /**
             * Size
             * @default 100
             */
            size?: number;
            /**
             * Seed
             * @default 20260927
             */
            seed?: number;
            /**
             * Design
             * @default v2
             * @enum {string}
             */
            design?: "v1" | "v2";
            /**
             * Force
             * @description Overwrite an existing dataset (loses its labels)
             * @default false
             */
            force?: boolean;
        };
        /** SampleResponse */
        SampleResponse: {
            /** Name */
            name: string;
            /** Issues */
            issues: number;
            /** Cases */
            cases: number;
            /** Strata Counts */
            strata_counts: {
                [key: string]: unknown;
            };
            /** Case Basis Counts */
            case_basis_counts: {
                [key: string]: unknown;
            };
        };
        /** ScanItemOut */
        ScanItemOut: {
            /** Issue Key */
            issue_key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Answer
             * @enum {string}
             */
            answer: "affected" | "not_affected" | "insufficient_information";
            /** Decided By */
            decided_by: string;
            /** Cached */
            cached: boolean;
            /** Fix Versions */
            fix_versions: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Dropped */
            dropped: components["schemas"]["DroppedEvidenceOut"][];
            /**
             * Error
             * @description Why the issue couldn't be answered, if it failed
             */
            error: string | null;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Kafka Version
             * @example 3.9.1
             */
            kafka_version: string;
            /**
             * Project
             * @default KAFKA
             */
            project?: string;
            /**
             * Since
             * @description Only issues updated since then, e.g. the last scan (alerting)
             */
            since?: string | null;
            /**
             * Limit
             * @description At most this many issues, newest first. Each one the fix versions don't settle costs a model call.
             * @default 50
             */
            limit?: number;
            /**
             * System
             * @description Default: the first registered system
             */
            system?: string | null;
        };
        /**
         * ScanResponse
         * @description The ``result`` of a finished scan job. Items: affected first, then
         *     insufficient_information, then not_affected; newest first within each.
         */
        ScanResponse: {
            /** Kafka Version */
            kafka_version: string;
            /** System */
            system: string;
            /** Since */
            since: string | null;
            /**
             * Candidates Total
             * @description Issues matching the filters, before the limit
             */
            candidates_total: number;
            /** Scanned */
            scanned: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Errors */
            errors: number;
            /**
             * Cached
             * @description Issues answered from stored facts, without a model call
             */
            cached: number;
            /** Items */
            items: components["schemas"]["ScanItemOut"][];
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Project
             * @default KAFKA
             */
            project?: string;
            /**
             * Full
             * @description Ignore the watermark and re-sync every issue
             * @default false
             */
            full?: boolean;
            /**
             * Request Delay
             * @description Seconds between JIRA requests
             * @default 1
             */
            request_delay?: number;
        };
        /** SyncState */
        SyncState: {
            /** Source */
            source: string;
            /**
             * Watermark
             * Format: date-time
             */
            watermark: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Name */
            name: string;
            /** Uploaded */
            uploaded: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_systems_systems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_jira_sync_sync_jira_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description A sync of this project is already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_state_sync_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncState"][];
                };
            };
        };
    };
    list_issues_issues_get: {
        parameters: {
            query?: {
                project?: string;
                /** @description Issue key, or text in the summary */
                q?: string | null;
                issue_type?: string | null;
                status?: string | null;
                resolution?: string | null;
                component?: string | null;
                affects_version?: string | null;
                fix_version?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_issue_issues__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_versions_get: {
        parameters: {
            query?: {
                project?: string;
                released?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KafkaVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Not returned here: the ``result`` of the job once it succeeds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_datasets_eval_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    sample_dataset_eval_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"];
                };
            };
            /** @description The dataset exists and force is false */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_status_eval_datasets__name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_eval_datasets__name__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_eval_runs_get: {
        parameters: {
            query?: {
                dataset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_eval_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_run_eval_runs__dataset___run_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset: string;
                run_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
