/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dependencies
         * @description The catalog of sources, in a fixed order, each marked if it has been added (synced).
         */
        get: operations["list_dependencies_dependencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Systems
         * @description Registered systems, the default (used when a request names none) first. Empty when no
         *     model is configured; ``/check`` and ``/scan`` then return 503.
         */
        get: operations["list_systems_systems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Jobs since the server started, newest first.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/jira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Jira Sync
         * @description Sync issues updated since the last run (or all, with ``full``). Poll ``/jobs/{id}``;
         *     ``progress`` counts issues synced so far.
         */
        post: operations["start_jira_sync_sync_jira_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Runs
         * @description The project's syncs, newest first: finished and failed ones, with what each fetched.
         */
        get: operations["sync_runs_sync_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync State
         * @description Watermark per source: everything updated before it has been synced.
         */
        get: operations["sync_state_sync_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Issues
         * @description Newest first. Version filters match a version name exactly; they don't compare versions.
         */
        get: operations["list_issues_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Issue */
        get: operations["get_issue_issues__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description Oldest first, ordered by the version module in the project's scheme (3.9.0 before
         *     3.10.0). Names that don't parse as versions come last.
         */
        get: operations["list_versions_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check
         * @description Is ``version`` affected by the issue? Decided by code from cited facts; the answer may be
         *     ``insufficient_information``. 422 when the issue's dependency isn't answered or the version
         *     isn't one of its releases; 502 when the system fails to read the issue (e.g. its model
         *     server is down); 503 until a system is registered.
         */
        post: operations["check_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{key}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stored Answer
         * @description The answer for ``version`` if it needs no model call: the fix versions settle it, or the
         *     system's facts for this issue are stored. Otherwise ``answered`` is false and ``POST /check``
         *     reads the issue.
         */
        get: operations["stored_answer_issues__key__answer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stored Answers
         * @description ``/issues/{key}/answer`` for a page of issues at once: each answered only from the fix
         *     versions or stored facts, never by calling the model. An issue that isn't synced is
         *     returned unanswered.
         */
        get: operations["stored_answers_answers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issue Stats
         * @description Counts over the synced issues, for the top of the issues page.
         */
        get: operations["issue_stats_stats_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Backlog
         * @description What a scan with the same filters would find, without calling the model: how many
         *     candidates the fix versions settle, how many have stored facts, and how many are not
         *     checked yet (each a model call).
         */
        get: operations["scan_backlog_scan_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Scan
         * @description Answer each candidate issue of ``project`` for ``version``: affected, not_affected or
         *     insufficient_information, with cited facts and a link. Poll ``/jobs/{id}``; ``progress``
         *     counts issues answered, and ``result`` is a ``ScanResponse``. One scan per system at a
         *     time, since they share the model server. 422 when the project's dependency isn't answered
         *     or the version isn't one of its releases.
         */
        post: operations["start_scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Upgrade
         * @description Compare each candidate issue's answer at ``from_version`` and ``to_version``: fixed by
         *     the move, new risks, no longer ruled out, still affected, inconclusive. Poll ``/jobs/{id}``;
         *     ``progress`` counts issues read, and ``result`` is an ``UpgradeResponse``. 422 when either
         *     version isn't a release of the project's dependency, or both are the same; 503 when
         *     ``read`` asks for model calls and no system is registered.
         */
        post: operations["start_upgrade_upgrade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repo/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Repo
         * @description Every dependency the manifests declare, grouped by family and version. Files that aren't
         *     manifests are ignored; paths are labels and are never opened on the server.
         */
        post: operations["scan_repo_repo_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description Synced issues per dependency, in DEPENDENCIES order: where the issues come from.
         */
        get: operations["sources_stats_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/issues/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly
         * @description Bugs filed and bugs fixed per calendar month (UTC), oldest first, the last ``months``
         *     months including the current one. Months with none are included as zero.
         */
        get: operations["monthly_stats_issues_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity
         * @description What is new in the project: issues created and resolved per day (UTC) over the last
         *     ``days`` days, including today; how many were created in the last 24 hours, 7 and 30 days;
         *     and the types of those created over ``days``.
         */
        get: operations["activity_stats_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reading Time
         * @description How long reading one issue took the model, over the stored extractions.
         */
        get: operations["reading_time_stats_reading_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_eval_datasets_get"];
        put?: never;
        /**
         * Sample Dataset
         * @description Sample issues and write a new dataset with an empty ``labels.csv``.
         */
        post: operations["sample_dataset_eval_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/datasets/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset Status
         * @description Labeling progress and problems.
         */
        get: operations["dataset_status_eval_datasets__name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/datasets/{name}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Dataset
         * @description Upload a fully labeled dataset to Langfuse.
         */
        post: operations["upload_dataset_eval_datasets__name__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Saved local runs, newest first.
         */
        get: operations["list_runs_eval_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Score a system on the dataset. Poll ``/jobs/{id}``; the result has the metrics, and local
         *     runs are saved under ``/eval/runs``.
         */
        post: operations["start_run_eval_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/runs/{dataset}/{run_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_eval_runs__dataset___run_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /**
             * Days
             * @description Oldest first, the last ``days`` days up to today
             */
            days: components["schemas"]["DayCount"][];
            /**
             * New 24H
             * @description Issues created in the last 24 hours
             */
            new_24h: number;
            /** New 7D */
            new_7d: number;
            /** New 30D */
            new_30d: number;
            /**
             * By Type
             * @description Issues created over ``days``, most first
             */
            by_type: components["schemas"]["TypeCount"][];
        };
        /** CheckRequest */
        CheckRequest: {
            /** Issue Key */
            issue_key: string;
            /**
             * Version
             * @description A release, in the scheme of the issue's dependency
             * @example 3.6.1
             */
            version: string;
            /**
             * System
             * @description Default: the first registered system
             */
            system?: string | null;
            /**
             * Refresh
             * @description Re-check: read the issue again and replace its stored facts. Has no effect when the fix versions settle the answer.
             * @default false
             */
            refresh?: boolean;
        };
        /** CheckResponse */
        CheckResponse: {
            /** Issue Key */
            issue_key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Version */
            version: string;
            /**
             * Answer
             * @enum {string}
             */
            answer: "affected" | "not_affected" | "insufficient_information";
            /** System */
            system: string;
            /**
             * Decided By
             * @description fix_versions when JIRA's fix versions settle it (the system isn't called); otherwise the system
             */
            decided_by: string;
            /**
             * Cached
             * @description The system's facts were stored from an earlier run
             */
            cached: boolean;
            /**
             * Fix Versions
             * @description Given as structured input, from JIRA
             */
            fix_versions: string[];
            /**
             * Evidence
             * @description Cited facts the decision used
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Dropped
             * @description Facts rejected, with the reason
             */
            dropped: components["schemas"]["DroppedEvidenceOut"][];
        };
        /** Comment */
        Comment: {
            /** Author */
            author: string | null;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DatasetStatus */
        DatasetStatus: {
            /** Name */
            name: string;
            /** Labeled */
            labeled: number;
            /** Total */
            total: number;
            /**
             * Problems
             * @description Problems other than unlabeled cases
             */
            problems: string[];
            /**
             * Ready
             * @description Fully labeled with no problems; can be uploaded
             */
            ready: boolean;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Name */
            name: string;
            /** Design */
            design: string;
            /** Labeled */
            labeled: number;
            /** Total */
            total: number;
        };
        /** DayCount */
        DayCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Created
             * @description Issues created that day (UTC)
             */
            created: number;
            /**
             * Bugs
             * @description Of those, bugs
             */
            bugs: number;
            /**
             * Resolved
             * @description Issues resolved that day and still resolved
             */
            resolved: number;
        };
        /** DependencyOut */
        DependencyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Project
             * @description Pass as `project` to /versions, /issues, /scan, /sync/jira
             */
            project: string;
            /** Tracker Url */
            tracker_url: string;
            /**
             * Watchable
             * @description Answered for a version; the others are only synced
             */
            watchable: boolean;
            /**
             * Added
             * @description Added as a source: some of its issues have been synced
             */
            added: boolean;
        };
        /** DetectedDependencyOut */
        DetectedDependencyOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Version
             * @description None when the manifests don't resolve it
             */
            version: string | null;
            /**
             * Family
             * @description A known family id, e.g. kafka or spark
             */
            family: string | null;
            /**
             * Ecosystem
             * @enum {string}
             */
            ecosystem: "maven" | "pypi" | "npm" | "image";
            /**
             * Watchable
             * @description Supported and at a known release: can be watched
             */
            watchable: boolean;
            /**
             * Reason
             * @description Why it can't be watched
             */
            reason: string | null;
            /** Artifacts */
            artifacts: string[];
            /** Files */
            files: string[];
            /**
             * Notes
             * @description How a version was read, e.g. from a Confluent image
             */
            notes: string[];
        };
        /** DroppedEvidenceOut */
        DroppedEvidenceOut: {
            /** Version */
            version: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "introduced" | "affects" | "unaffected" | "fix";
            /** Quote */
            quote: string;
            /** Reason */
            reason: string;
        };
        /** EvalRun */
        EvalRun: {
            /** Run Name */
            run_name: string;
            /** System */
            system: string;
            /** Dataset */
            dataset: string;
            /** Provisional */
            provisional: boolean;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** EvalRunRequest */
        EvalRunRequest: {
            /**
             * Dataset
             * @default kafka-ground-truth-v2
             */
            dataset?: string;
            /**
             * System
             * @description A registered system; runs are compared with each other
             */
            system: string;
            /**
             * Run Name
             * @description Default: <system>-<UTC timestamp>
             */
            run_name?: string | null;
            /**
             * Provisional
             * @description Score against JIRA metadata answers; allowed before labeling is done
             * @default false
             */
            provisional?: boolean;
            /**
             * Langfuse
             * @description Run as a Langfuse experiment on the dataset
             * @default false
             */
            langfuse?: boolean;
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Run Name */
            run_name: string;
            /** System */
            system: string;
            /** Dataset */
            dataset: string;
            /** Provisional */
            provisional: boolean;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Version */
            version: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "introduced" | "affects" | "unaffected" | "fix";
            /** Quote */
            quote: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Db Revision */
            db_revision: string | null;
        };
        /** IssueAnswer */
        IssueAnswer: {
            /** Issue Key */
            issue_key: string;
            /**
             * Answered
             * @description False when only a model call (POST /check) can answer
             */
            answered: boolean;
            result?: components["schemas"]["CheckResponse"] | null;
        };
        /** IssueDetail */
        IssueDetail: {
            /** Key */
            key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Issue Type */
            issue_type: string | null;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /** Priority */
            priority: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Project */
            project: string;
            /** Description */
            description: string | null;
            /** Labels */
            labels: string[];
            /** Components */
            components: string[];
            /** Affects Versions */
            affects_versions: string[];
            /** Fix Versions */
            fix_versions: string[];
            /** Comments */
            comments: components["schemas"]["Comment"][];
        };
        /** IssuePage */
        IssuePage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["IssueSummary"][];
        };
        /** IssueStats */
        IssueStats: {
            /** Total */
            total: number;
            /** Bugs */
            bugs: number;
            /** Open Bugs */
            open_bugs: number;
            /** Fixed Bugs */
            fixed_bugs: number;
            /**
             * Read
             * @description Issues whose text a model has read (facts stored)
             */
            read: number;
            /**
             * Newest
             * @description The most recent update among synced issues
             */
            newest: string | null;
        };
        /** IssueSummary */
        IssueSummary: {
            /** Key */
            key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Issue Type */
            issue_type: string | null;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /** Priority */
            priority: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Key */
            key: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Progress */
            progress: number;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** MonthCount */
        MonthCount: {
            /**
             * Month
             * @example 2026-09
             */
            month: string;
            /**
             * Filed
             * @description Bugs created that month
             */
            filed: number;
            /**
             * Fixed
             * @description Bugs resolved as Fixed that month
             */
            fixed: number;
        };
        /** ReadingTime */
        ReadingTime: {
            /**
             * Count
             * @description Stored extractions
             */
            count: number;
            /** Median Ms */
            median_ms: number | null;
            /** P90 Ms */
            p90_ms: number | null;
            /** Bins */
            bins: components["schemas"]["ReadingTimeBin"][];
        };
        /** ReadingTimeBin */
        ReadingTimeBin: {
            /** From S */
            from_s: number;
            /**
             * To S
             * @description None for the last bin: everything slower
             */
            to_s: number | null;
            /** Count */
            count: number;
        };
        /** ReleaseVersion */
        ReleaseVersion: {
            /** Name */
            name: string;
            /** Released */
            released: boolean;
            /** Archived */
            archived: boolean;
            /** Release Date */
            release_date: string | null;
        };
        /** RepoFile */
        RepoFile: {
            /**
             * Path
             * @description Path in the repository; a label only
             */
            path: string;
            /** Content */
            content: string;
        };
        /** RepoScanRequest */
        RepoScanRequest: {
            /**
             * Files
             * @description Manifest files and their text
             */
            files: components["schemas"]["RepoFile"][];
        };
        /** RepoScanResponse */
        RepoScanResponse: {
            /** Files Read */
            files_read: string[];
            /** Dependencies */
            dependencies: components["schemas"]["DetectedDependencyOut"][];
        };
        /** SampleRequest */
        SampleRequest: {
            /** Name */
            name: string;
            /**
             * Size
             * @default 100
             */
            size?: number;
            /**
             * Seed
             * @default 20260927
             */
            seed?: number;
            /**
             * Design
             * @default v2
             * @enum {string}
             */
            design?: "v1" | "v2";
            /**
             * Force
             * @description Overwrite an existing dataset (loses its labels)
             * @default false
             */
            force?: boolean;
        };
        /** SampleResponse */
        SampleResponse: {
            /** Name */
            name: string;
            /** Issues */
            issues: number;
            /** Cases */
            cases: number;
            /** Strata Counts */
            strata_counts: {
                [key: string]: unknown;
            };
            /** Case Basis Counts */
            case_basis_counts: {
                [key: string]: unknown;
            };
        };
        /** ScanBacklog */
        ScanBacklog: {
            /** Project */
            project: string;
            /** Version */
            version: string;
            /** Since */
            since: string | null;
            /**
             * System
             * @description The system whose stored facts count as checked
             */
            system: string | null;
            /**
             * Candidates
             * @description Issues a scan would answer, before its limit
             */
            candidates: number;
            /**
             * Settled
             * @description Answered by the fix versions, without a model call
             */
            settled: number;
            /**
             * Checked
             * @description Answered from the system's stored facts
             */
            checked: number;
            /**
             * Unchecked
             * @description Not checked yet: each takes a model call in a scan
             */
            unchecked: number;
        };
        /** ScanItemOut */
        ScanItemOut: {
            /** Issue Key */
            issue_key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Answer
             * @enum {string}
             */
            answer: "affected" | "not_affected" | "insufficient_information";
            /** Decided By */
            decided_by: string;
            /** Cached */
            cached: boolean;
            /** Fix Versions */
            fix_versions: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Dropped */
            dropped: components["schemas"]["DroppedEvidenceOut"][];
            /**
             * Error
             * @description Why the issue couldn't be answered, if it failed
             */
            error: string | null;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Project
             * @description The dependency's project
             * @example KAFKA
             */
            project: string;
            /**
             * Version
             * @description A release, in the dependency's scheme
             * @example 3.9.1
             */
            version: string;
            /**
             * Since
             * @description Only issues updated since then, e.g. the last scan (alerting)
             */
            since?: string | null;
            /**
             * Limit
             * @description At most this many issues, newest first. Each one the fix versions don't settle costs a model call.
             * @default 50
             */
            limit?: number;
            /**
             * System
             * @description Default: the first registered system
             */
            system?: string | null;
        };
        /**
         * ScanResponse
         * @description The ``result`` of a finished scan job. Items: affected first, then
         *     insufficient_information, then not_affected; newest first within each.
         */
        ScanResponse: {
            /** Version */
            version: string;
            /** System */
            system: string;
            /** Since */
            since: string | null;
            /**
             * Candidates Total
             * @description Issues matching the filters, before the limit
             */
            candidates_total: number;
            /** Scanned */
            scanned: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Errors */
            errors: number;
            /**
             * Cached
             * @description Issues answered from stored facts, without a model call
             */
            cached: number;
            /** Items */
            items: components["schemas"]["ScanItemOut"][];
        };
        /** SourceCount */
        SourceCount: {
            /** Dependency */
            dependency: string;
            /** Name */
            name: string;
            /** Project */
            project: string;
            /**
             * Added
             * @description Some of its issues have been synced
             */
            added: boolean;
            /** Issues */
            issues: number;
            /** Bugs */
            bugs: number;
            /** Open Bugs */
            open_bugs: number;
            /**
             * Synced At
             * @description The sync watermark; None if never synced
             */
            synced_at: string | null;
        };
        /** StoredAnswer */
        StoredAnswer: {
            /**
             * Answered
             * @description False when only a model call (POST /check) can answer
             */
            answered: boolean;
            /** System */
            system: string | null;
            result?: components["schemas"]["CheckResponse"] | null;
        };
        /** StoredAnswers */
        StoredAnswers: {
            /** Version */
            version: string;
            /** System */
            system: string | null;
            /**
             * Items
             * @description In the order the keys were given
             */
            items: components["schemas"]["IssueAnswer"][];
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Project
             * @example KAFKA
             */
            project: string;
            /**
             * Full
             * @description Ignore the watermark and re-sync every issue
             * @default false
             */
            full?: boolean;
            /**
             * Request Delay
             * @description Seconds between JIRA requests
             * @default 1
             */
            request_delay?: number;
        };
        /** SyncRun */
        SyncRun: {
            /** Source */
            source: string;
            /** Full */
            full: boolean;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "failed";
            /**
             * Fetched
             * @description Issues written, new or updated
             */
            fetched: number;
            /**
             * New Issues
             * @description Issues the database didn't have before
             */
            new_issues: number;
            /** Error */
            error: string | null;
        };
        /** SyncState */
        SyncState: {
            /** Source */
            source: string;
            /**
             * Watermark
             * Format: date-time
             */
            watermark: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TypeCount */
        TypeCount: {
            /** Issue Type */
            issue_type: string;
            /** Count */
            count: number;
        };
        /** UpgradeItemOut */
        UpgradeItemOut: {
            /** Issue Key */
            issue_key: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Status */
            status: string | null;
            /** Resolution */
            resolution: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Fix Versions */
            fix_versions: string[];
            /**
             * Current
             * @description The answer at from_version
             * @enum {string}
             */
            current: "affected" | "not_affected" | "insufficient_information";
            /**
             * Target
             * @description The answer at to_version
             * @enum {string}
             */
            target: "affected" | "not_affected" | "insufficient_information";
            /**
             * Change
             * @enum {string}
             */
            change: "new_risk" | "remains" | "exposed" | "fixed" | "inconclusive" | "fix_included";
            /**
             * Decided By
             * @description The system, when its facts were used; else fix_versions
             */
            decided_by: string;
            /** Cached */
            cached: boolean;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Dropped */
            dropped: components["schemas"]["DroppedEvidenceOut"][];
            /** Error */
            error: string | null;
        };
        /** UpgradeRequest */
        UpgradeRequest: {
            /**
             * Project
             * @example KAFKA
             */
            project: string;
            /**
             * From Version
             * @description The version you run
             * @example 3.4.0
             */
            from_version: string;
            /**
             * To Version
             * @description The version to move to
             * @example 3.9.1
             */
            to_version: string;
            /**
             * Read
             * @description Read at most this many issues without stored facts (each a model call), those that may affect the target first (upgrade.read_order). 0: stored facts and fix versions only
             * @default 0
             */
            read?: number;
            /**
             * System
             * @description Default: the first registered system
             */
            system?: string | null;
        };
        /**
         * UpgradeResponse
         * @description The ``result`` of a finished upgrade job. Items: new_risk, remains, exposed, fixed,
         *     inconclusive, then fix_included; newest first within each. Issues not affected at either version
         *     are only counted (``unchanged``), as are those never read (``unchecked``).
         */
        UpgradeResponse: {
            /** Project */
            project: string;
            /** From Version */
            from_version: string;
            /** To Version */
            to_version: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "upgrade" | "downgrade";
            /** System */
            system: string | null;
            /**
             * Candidates
             * @description Candidate bugs compared
             */
            candidates: number;
            /**
             * Releases Between
             * @description Releases after the lower version, up to the higher
             */
            releases_between: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Unchecked
             * @description Inconclusive at the target and never read by the model
             */
            unchecked: number;
            /**
             * Read
             * @description Issues the model read in this run
             */
            read: number;
            /** Errors */
            errors: number;
            /** Items */
            items: components["schemas"]["UpgradeItemOut"][];
        };
        /** UploadResponse */
        UploadResponse: {
            /** Name */
            name: string;
            /** Uploaded */
            uploaded: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_dependencies_dependencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyOut"][];
                };
            };
        };
    };
    list_systems_systems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_jira_sync_sync_jira_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description A sync of this project is already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_runs_sync_runs_get: {
        parameters: {
            query: {
                project: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_state_sync_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncState"][];
                };
            };
        };
    };
    list_issues_issues_get: {
        parameters: {
            query: {
                project: string;
                /** @description Issue key, or text in the summary */
                q?: string | null;
                issue_type?: string | null;
                status?: string | null;
                resolution?: string | null;
                component?: string | null;
                affects_version?: string | null;
                fix_version?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_issue_issues__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_versions_get: {
        parameters: {
            query: {
                project: string;
                released?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stored_answer_issues__key__answer_get: {
        parameters: {
            query: {
                version: string;
                system?: string | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredAnswer"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stored_answers_answers_get: {
        parameters: {
            query: {
                version: string;
                /** @description Issue keys */
                key: string[];
                system?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredAnswers"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issue_stats_stats_issues_get: {
        parameters: {
            query: {
                project: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_backlog_scan_backlog_get: {
        parameters: {
            query: {
                project: string;
                version: string;
                since?: string | null;
                system?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanBacklog"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Not returned here: the ``result`` of the job once it succeeds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_upgrade_upgrade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpgradeRequest"];
            };
        };
        responses: {
            /** @description Not returned here: the ``result`` of the job once it succeeds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradeResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scan_repo_repo_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_stats_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCount"][];
                };
            };
        };
    };
    monthly_stats_issues_monthly_get: {
        parameters: {
            query: {
                project: string;
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthCount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_stats_activity_get: {
        parameters: {
            query: {
                project: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reading_time_stats_reading_get: {
        parameters: {
            query: {
                project: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingTime"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_eval_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    sample_dataset_eval_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"];
                };
            };
            /** @description The dataset exists and force is false */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_status_eval_datasets__name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_eval_datasets__name__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_eval_runs_get: {
        parameters: {
            query?: {
                dataset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_eval_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_run_eval_runs__dataset___run_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset: string;
                run_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
