"""jira versions

Revision ID: f429b82b8cb4
Revises: 502cd7866ccf
Create Date: 2026-09-27 17:19:35.855122
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f429b82b8cb4"
down_revision: str | Sequence[str] | None = "502cd7866ccf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jira_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("project", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("released", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project", "name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jira_versions")
    # ### end Alembic commands ###
