"""sync runs

Revision ID: 41a29d4127bb
Revises: 6648ff2b1a5b
Create Date: 2026-10-05 16:49:51.880528
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "41a29d4127bb"
down_revision: str | Sequence[str] | None = "6648ff2b1a5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("full", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("fetched", sa.BigInteger(), nullable=False),
        sa.Column("new_issues", sa.BigInteger(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint("status IN ('succeeded', 'failed')", name="sync_runs_status_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_runs_source_started_at", "sync_runs", ["source", "started_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_runs_source_started_at", table_name="sync_runs")
    op.drop_table("sync_runs")
    # ### end Alembic commands ###
