"""Postgres engine, sessions and schema migrations.

The schema is defined once, as SQLAlchemy models in ``dep_watch_agent.orm``. Migrations are
Alembic revisions in ``dep_watch_agent/migrations/versions``, autogenerated from the models:
``uv run alembic revision --autogenerate -m "..."``.
"""

import os

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from sqlalchemy import Engine, create_engine, pool
from sqlalchemy.orm import Session, sessionmaker

DEFAULT_DATABASE_URL = "postgresql://dep_watch:dep_watch@localhost:5433/dep_watch"

# Arbitrary constant identifying the migration lock among this app's advisory locks.
MIGRATION_LOCK_ID = 7_361_204_518


def database_url() -> str:
    return os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL)


def sqlalchemy_url(url: str) -> str:
    """Point a plain ``postgresql://`` URL at SQLAlchemy's psycopg 3 driver."""
    for prefix in ("postgresql://", "postgres://"):
        if url.startswith(prefix):
            return "postgresql+psycopg://" + url.removeprefix(prefix)
    return url


def create_db_engine(url: str | None = None, *, schema: str | None = None) -> Engine:
    """Engine for ``url`` (default: ``DATABASE_URL``), optionally pinned to one schema."""
    connect_args = {"options": f"-csearch_path={schema}"} if schema else {}
    return create_engine(
        sqlalchemy_url(url or database_url()), poolclass=pool.NullPool, connect_args=connect_args
    )


def session_factory(engine: Engine | None = None) -> sessionmaker[Session]:
    return sessionmaker(engine or create_db_engine())


def alembic_config(url: str | None = None, *, schema: str | None = None) -> Config:
    config = Config()
    config.set_main_option("script_location", "dep_watch_agent:migrations")
    config.attributes["url"] = url or database_url()
    config.attributes["schema"] = schema
    return config


def migrate(url: str | None = None, *, schema: str | None = None, revision: str = "head") -> None:
    """Upgrade the database (or one schema in it) to ``revision``."""
    command.upgrade(alembic_config(url, schema=schema), revision)


def current_revision(url: str | None = None, *, schema: str | None = None) -> str | None:
    with create_db_engine(url, schema=schema).connect() as connection:
        return MigrationContext.configure(connection).get_current_revision()
